def on_a_pressed():
    global bubbleNumber
    bubble.toss_bubble()
    bubble.load_bubble()
    bubbleNumber += -1
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_left_pressed():
    bubble.tilt_angle(bubble.Choice.LEFT)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_hit_wall(sprite, location):
    bubble.stick_to_wall(sprite, location)
scene.on_hit_wall(SpriteKind.bubble, on_hit_wall)

def on_right_pressed():
    bubble.tilt_angle(bubble.Choice.RIGHT)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

bubbleNumber = 80
bubble.create_board()
bubble.load_bubble()
mySprite = sprites.create(img("""
        ..........................dddd
        ..........6...............dd..
        ...........66..6666......ddd..
        ..........66666666667....dd...
        ......d...676666667667..ddd...
        .dddddd...667666666766..dd....
        .dddddd....667777766676ddd....
        ......dd...667dd7777767dd.....
        .......dd..66cd961dd977dd.....
        ........dd.666d86fdd6fbc......
        .........dd.6d6dddddbdd.......
        ..........dd6bddedddddb.......
        ...........ddcdddeebdda.......
        ............bcbddddddac.......
        ............caaaabbbaa........
        .............a5aaabaa5........
        ..............aaaaaaaa........
        ..............aa7aa55.........
        ...............a55555.........
        ...............a55575.........
        ...............a55555.........
        ...............aa5555.........
        ................aaaaa.........
        ...............a55555.........
        ..............aaaaaaa.........
        ..............a555555.........
        .............a5555555.........
        ............aaaaa5555.........
        ...........aa55555555.........
        ..........aa555a555555........
        ..........a55aaa555555........
        .........a555aa5555a755.......
        ........aa55aa57555a555.......
        .......aa55aa555555a555.......
        .......a55aa555a555a555a......
        ........aaaaaaaaaaaaaaaa......
        ..........bbbb...bbb..........
        ..........ddd....ddd..........
        .........ddd.....ddd..........
        ........ddd......ddd..........
        .......dddd......ddd..........
        ......dddd.......ddd..........
        ......ddd.........dd..........
        .....ddd..........dd..........
        .....dd...........dd..........
        ....ddd............dd.........
        ....dd.............ddd........
        ....dddd.............dd.......
        ..............................
        ..............................
        """),
    SpriteKind.player)
mySprite.top = 102

def on_on_update():
    info.set_score(bubbleNumber)
    if info.score() == 0:
        game.game_over(False)
game.on_update(on_on_update)
